version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  migrations:
    image: golang:1.22.5 
    container_name: migrations
    depends_on:
      - mysql
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - app-network
    entrypoint: >
      sh -c "
      echo 'Instalando o cliente MySQL...';
      apt-get update && apt-get install -y default-mysql-client && \
      echo 'Aguardando o MySQL iniciar...';
      until mysql -h mysql -u root -proot -e 'SELECT 1' > /dev/null 2>&1; do
        echo 'MySQL ainda não está pronto...';
        sleep 2;
      done;
      echo 'MySQL pronto! Iniciando as migrations...';
      go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest && \
      /go/bin/migrate -path=internal/infra/database/migrations -database 'mysql://root:root@tcp(mysql:3306)/orders' -verbose up;
      "

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
